name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        distribution-id : ${{ secrets.DISTRIBUTION_ID }}
      run: |
        echo $aws-access-key-id >> secrets.txt
        echo $aws-secret-access-key >> secrets.txt
        echo $AWS_S3_BUCKET >> secrets.txt
        echo $distribution-id >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
